const Constants = {
    ADD_BANKS: 'ADD_BANKS',
    ADD_TRANSACTIONS: 'ADD_TRANSACTIONS',
    REMOVE_TRANSACTIONS: 'REMOVE_TRANSACTIONS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOAD_TRANSACTIONS_REQUEST: 'LOAD_TRANSACTIONS_REQUEST',
    LOAD_TRANSACTIONS_SUCCESS: 'LOAD_TRANSACTIONS_SUCCESS',
    LOAD_BANKS_REQUEST: 'LOAD_BANKS_REQUEST',
    LOAD_BANKS_SUCCESS: 'LOAD_BANKS_SUCCESS',
    CHANGE_TRANSACTION_FORM_MODEL: 'CHANGE_TRANSACTION_FORM_MODEL',
    SET_TRANSACTION_FORM_ERRORS: 'SET_TRANSACTION_FORM_ERRORS',
    CHANGE_LOGIN_FORM_MODEL: 'CHANGE_LOGIN_FORM_MODEL',
    SET_LOGIN_FORM_ERRORS: 'SET_LOGIN_FORM_ERRORS',
    POST_TRANSACTION_REQUEST: 'POST_TRANSACTION_REQUEST',
    POST_TRANSACTION_SUCCESS: 'POST_TRANSACTION_SUCCESS',
    RESET_TRANSACTION_FORM: 'RESET_TRANSACTION_FORM',
    RESET_LOGIN_FORM: 'RESET_LOGIN_FORM',
};

export default Constants;
